ShortenerApp/urls.py
from django.conf.urls import include,url
from ShortenerApp import views

urlpatterns = [

    url(r'^$',views.index,name='home' ),
    # for our home/index page
    url(r'^(?P<short_id>\w{6})$',views.redirect_original,name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
    url(r'^makeshort/$',views.shorten_url,name='shorturl'),
    # this will create a URL's short id and return the short URL

]

UrlShortener/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ShortenerApp.urls',namespace='ShortenerApp')),
]

ShortenerApp/models.py
from django.db import models

# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6, primary_key=True)
    httpurl = models.URLField(max_length=200)
    date_submitted = models.DateTimeField(auto_now=True)
    usage_count = models.IntegerField(default=0)


def __str__(self):
    return self.httpurl

ShortenerApp/views.py
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from ShortenerApp.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def index(request):
    c = {}
    c.update(request)
    return render_to_response('ShortenerApp/index.html', c)

def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id)
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.http)

@csrf_exempt
def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id)
        b.save()

        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

ShortenerApp/templates/ShortenerApp/base.html
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}Welcome to mysite{% endblock %}</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'ShortenerApp/css/Shortener.css' %}" />
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});
function returnSuccess(data, textStatus, jqXHR) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 } else {
 $('#url-result').text("Please Enter a URL !");
 }
}
</script>
<body style="font-size:300%;text-align:center;background-image:url('http://www.wallpaperscharlie.com/wp-content/uploads/2016/06/Love-Couples-HD-Wallpapers-1080p-Widescreen-4.jpg')">
<div id="wrap">
<header>
 <h1 style="font-size:200%;text-align:center;"><a href="{% url 'ShortenerApp:home' %}">URL Shortner</a><small>Shorten the URL</small></h1>
</header>

<div id="content">
{% block content %}

{% endblock %}
</div>
</div>
</body>
</html>

ShortenerApp/templates/ShortenerApp/index.html
{% extends "ShortenerApp/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}
     <a style="align:right" href="https://github.com/Nidhintsajee/Url-Shortener-App">Github Link</a>

 <div class="panel-body">
 <div class="col-sm-9">

 <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.github.com" />
 </div>
 <div class="col-sm-3">
 {% csrf_token %}
 <button id="submitButton" class="btn btn-primary">Submit</button></p>
 </div>
 </div>
 <span id="url-result">Enter the URL above and click submit!</span>

{% endblock %}